### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Petelin** [dfuse-io/eosws-go#4]
RegisterOutgoingMessage("get_actions", GetActionTraces{})

not get_action_tracexxx

and this library is a little buggy.

**Comment by abourget** [comment]
Thanks for catching that.

What is buggy otherwise? This is a new library, we're just starting to dogfood it and appreciate feedback!

**Comment by abourget** [comment]
The latest code has the proper outgoing message registered.

Update the lib and see if it works now. Thanks!

**Comment by Petelin** [comment]
the problem is doc update get_action_traces, but the dfuse server still not accept it. and curl https://mainnet.eos.dfuse.io/v1/chain/get_info is not working too.

**Comment by Petelin** [comment]
here is another bug:
type Listening struct {
	CommonOut
	NextBlock uint32 `json:"data"`
}

data -> should be next_block

**Comment by abourget** [comment]
Rolled out a fix both server side and client side. Please update your
library, and close this issue if it is satisfactory.
