### ISSUE TITLE
how can is use push action feature

### ISSUE THREAD

**Issue by KePeng1019** [dfuse-io/eosws-go#5]
hou can i use push action use golang code with dfuse restful api

**Comment by abourget** [comment]
See how `eosc` does it https://github.com/eoscanada/eosc/blob/master/eosc/cmd/common.go

You simply add a `api.Header.Set("X-Eos-Push-Guarantee", "in-block")` to the `eos.API` instance.. and it'll use that when pushing transactions through the normal `PushTransaction` .. you'll also need to add a `Bearer` token as another header.. and then you're good to go.

**Comment by KePeng1019** [comment]
ok,thanks

**Comment by KePeng1019** [comment]
but my my
 `eos.API` instance do not have Header params. i am using `"github.com/eoscanada/eos-go" ` lib,
```golang
type API struct {
	HttpClient              *http.Client
	BaseURL                 string
	Signer                  Signer
	Debug                   bool
	Compress                CompressionType
	DefaultMaxCPUUsageMS    uint8
	DefaultMaxNetUsageWords uint32 // in 8-bytes words

	lastGetInfo      *InfoResp
	lastGetInfoStamp time.Time
	lastGetInfoLock  sync.Mutex

	customGetRequiredKeys func(tx *Transaction) ([]ecc.PublicKey, error)
}
```
this is my eoscanada golang lib eos api instance look like.

**Comment by maoueh** [comment]
You are not up to date against the `github.com/eoscanada/eos-go` library. Latest version of `eos-go` has the `Header` field in it: https://github.com/eoscanada/eos-go/blob/master/api.go#L27.

Can you check that.

**Comment by KePeng1019** [comment]
thanks. I update eos-go lib and i works
